78 test lrp
dianna-ai/dianna-exploration pull request #113
Opened 2021-07-27 12:23 UTC by geek-yang

Explore LRP algorithm on MNIST and geometric shapes data sets. 
(fix small typos in one deepliftshap notebook as well, changes are minor and only related to markdowns).

2021-08-25 12:01 UTC, cwmeijer requested changes
I posted some comments on the binary mnist dataset here:
https://app.reviewnb.com/dianna-ai/dianna-exploration/blob/78-test-LRP/example_data%2Fxai_method_study%2FLRP%2FLRP_mnist_binary.ipynb%2F/file

The only 2 things that I would like to be changed before approval are a conclusion text block for both notebooks. Could be very short, one line even. But I think that would be very valuable.

Other than that, it looks very good. Great job!

2021-08-25 12:01 UTC, cwmeijer commented on example_data/xai_method_study/SHAP/DeepLiftSHAP_geometric_shapes.ipynb
> -    "# load binary MNIST from local\n",
👍

2021-08-25 12:01 UTC, cwmeijer commented on example_data/xai_method_study/LRP/LRP_geometric_shapes.ipynb
> +{
<p>Again, please add some conclusion.</p><p>Also, very hard to see what we should learn from these heatmaps. This is also a result of the rather difficult dataset we created. I wouldn't know myself what pixels I would expect to be important.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/dianna-ai/dianna-exploration/pull/113/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='12'/>

2021-09-07 07:43 UTC, geek-yang commented on example_data/xai_method_study/LRP/LRP_geometric_shapes.ipynb
> +{
I add a short conclusion in the notebook. Thanks for the comment!

2021-09-07 07:44 UTC, geek-yang commented on example_data/xai_method_study/SHAP/DeepLiftSHAP_geometric_shapes.ipynb
> -    "# load binary MNIST from local\n",
Thanks for your comments, Chris. Please find my response via the ReviewNB inside the notebook.

2021-09-07 08:23 UTC, cwmeijer approved these changes

2021-09-16 19:53 UTC, merged