Single deletion
dianna-ai/dianna-exploration pull request #163
Opened 2023-05-19 13:52 UTC by WillemSpek

Implemenation of single Deletion for text methods. Tutorial is included in the `metrics_text.ipynb`. Example visualization is given below: 

![LIMEtext](https://github.com/dianna-ai/dianna-exploration/assets/33344129/7930a9ef-61ba-436e-bf1a-cc87fff1300e)

2023-05-22 13:27 UTC, elboyran reviewed
Looks OK, did you address Chri's comments? Also, I see a type error in one notebook, does it actually run successfully?

2023-05-30 09:21 UTC, cwmeijer commented on relevance_maps_properties/metrics/metrics_text.ipynb
> +{
<p>Why do you conclude this for RISE? I only see LIME being used in this notebook.</p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/dianna-ai/dianna-exploration/pull/163/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='12'/>

2023-05-30 09:21 UTC, cwmeijer commented on relevance_maps_properties/metrics/metrics_tutorial.ipynb
> +{
<p>This is an awesome figure!</p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/dianna-ai/dianna-exploration/pull/163/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='13'/>

2023-05-30 09:21 UTC, cwmeijer commented on relevance_maps_properties/metrics/metrics_tutorial.ipynb
> +{
<p>I don't understand this Figure. What is compared with what? At 40% removal, we see a dramatic drop. This means, that after removing 40% of the most important parts according to our XAI method, the models performance suddenly drops. Is this correct? We already saw the same thing in the Figure above. What does this Figure add then? If it's just another (maybe more detailed) visualization of the same thing, then say so in the comments. It's now a little surprising. Also, in that case, I would have expected a second data series in the same plot showing the 'random order' deletion strategy.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/dianna-ai/dianna-exploration/pull/163/discussion/#comment-1209992594'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='15'/>

2023-05-30 09:22 UTC, cwmeijer requested changes
See comments in the bee and text notebooks

2023-05-30 11:59 UTC, WillemSpek commented on relevance_maps_properties/metrics/metrics_tutorial.ipynb
> +{
Idea of the images is to give the user a visual idea of what's going on. What is actually interesting is the area under the deletion curve or between the deletion and the random curve for the experiments (i.e. a concrete number when can compare across experiments). I see why you find this unclear, I will add some verbosity to the notebooks :)

2023-05-30 12:00 UTC, WillemSpek commented on relevance_maps_properties/metrics/metrics_text.ipynb
> +{
Thanks, I experimented on both but only show one result in the notebook. Will factor in both LIME and RISE and compare their scores and visualizations in the notebook.

2023-05-30 12:00 UTC, WillemSpek commented on relevance_maps_properties/metrics/metrics_tutorial.ipynb
> +{
Thanks :)

2023-05-30 14:21 UTC, WillemSpek commented
I have addressed your changes by making the notebooks far clearer :) Had to deal with some annoying merge conflicts because I created this branch from incremental deletion which received quite a few changes since its PR conversion, but all should be fine now. Feel free to review the changes.

2023-06-01 14:07 UTC, cwmeijer approved these changes
Looks great now! Thanks!

2023-06-01 14:41 UTC, merged